export const multiOptions = [
    { value: "Math", text: "Mathematics", selected: false },
    { value: "English", text: "English", selected: false },
    { value: "Physics", text: "Physics", selected: false },
    { value: "Chemistry", text: "Chemistry", selected: false },
    { value: "Biology", text: "Biology", selected: false },
    { value: "History", text: "History", selected: false },
    { value: "Geography", text: "Geography", selected: false },
    { value: "Philosophy", text: "Philosophy", selected: false },
    { value: "Sociology", text: "Sociology", selected: false },
    { value: "Psychology", text: "Psychology", selected: false },
    { value: "Economics", text: "Economics", selected: false },
    { value: "Business", text: "Business Administration", selected: false },
    { value: "Accounting", text: "Accounting", selected: false },
    { value: "Marketing", text: "Marketing", selected: false },
    { value: "Computer_Science", text: "Computer Science", selected: false },
    { value: "Programming", text: "Programming", selected: false },
    { value: "Web_Development", text: "Web Development", selected: false },
    { value: "Artificial_Intelligence", text: "Artificial Intelligence", selected: false },
    { value: "Data_Science", text: "Data Science", selected: false },
    { value: "Cybersecurity", text: "Cybersecurity", selected: false },
    { value: "Medicine", text: "Medicine", selected: false },
    { value: "Nursing", text: "Nursing", selected: false },
    { value: "Pharmacy", text: "Pharmacy", selected: false },
    { value: "Dentistry", text: "Dentistry", selected: false },
    { value: "Physiotherapy", text: "Physiotherapy", selected: false },
    { value: "Sports_Science", text: "Sports Science", selected: false },
    { value: "Law", text: "Law", selected: false },
    { value: "Political_Science", text: "Political Science", selected: false },
    { value: "Engineering", text: "Engineering", selected: false },
    { value: "Mechanical_Engineering", text: "Mechanical Engineering", selected: false },
    { value: "Civil_Engineering", text: "Civil Engineering", selected: false },
    { value: "Electrical_Engineering", text: "Electrical Engineering", selected: false },
    { value: "Architecture", text: "Architecture", selected: false },
    { value: "Agronomy", text: "Agronomy", selected: false },
    { value: "Veterinary", text: "Veterinary Medicine", selected: false },
    { value: "Music", text: "Music", selected: false },
    { value: "Theater", text: "Theater", selected: false },
    { value: "Arts", text: "Arts", selected: false },
    { value: "Photography", text: "Photography", selected: false },
    { value: "Journalism", text: "Journalism", selected: false },
    { value: "Foreign_Languages", text: "Foreign Languages", selected: false },
    { value: "Pedagogy", text: "Pedagogy", selected: false },
  ];
  