export const multiOptions = [
    { value: "Matematica", text: "Matemática", selected: false },
    { value: "Ingles", text: "Inglês", selected: false },
    { value: "Fisica", text: "Física", selected: false },
    { value: "Quimica", text: "Química", selected: false },
    { value: "Biologia", text: "Biologia", selected: false },
    { value: "Historia", text: "História", selected: false },
    { value: "Geografia", text: "Geografia", selected: false },
    { value: "Filosofia", text: "Filosofia", selected: false },
    { value: "Sociologia", text: "Sociologia", selected: false },
    { value: "Psicologia", text: "Psicologia", selected: false },
    { value: "Economia", text: "Economia", selected: false },
    { value: "Administracao", text: "Administração", selected: false },
    { value: "Contabilidade", text: "Contabilidade", selected: false },
    { value: "Marketing", text: "Marketing", selected: false },
    { value: "Ciencia_Computacao", text: "Ciência da Computação", selected: false },
    { value: "Programacao", text: "Programação", selected: false },
    { value: "Desenvolvimento_Web", text: "Desenvolvimento Web", selected: false },
    { value: "Inteligencia_Artificial", text: "Inteligência Artificial", selected: false },
    { value: "Ciencia_Dados", text: "Ciência de Dados", selected: false },
    { value: "Seguranca_Cibernetica", text: "Segurança Cibernética", selected: false },
    { value: "Medicina", text: "Medicina", selected: false },
    { value: "Enfermagem", text: "Enfermagem", selected: false },
    { value: "Farmacia", text: "Farmácia", selected: false },
    { value: "Odontologia", text: "Odontologia", selected: false },
    { value: "Fisioterapia", text: "Fisioterapia", selected: false },
    { value: "Ciencia_Esportes", text: "Ciência do Esporte", selected: false },
    { value: "Direito", text: "Direito", selected: false },
    { value: "Ciencia_Politica", text: "Ciência Política", selected: false },
    { value: "Engenharia", text: "Engenharia", selected: false },
    { value: "Engenharia_Mecanica", text: "Engenharia Mecânica", selected: false },
    { value: "Engenharia_Civil", text: "Engenharia Civil", selected: false },
    { value: "Engenharia_Eletrica", text: "Engenharia Elétrica", selected: false },
    { value: "Arquitetura", text: "Arquitetura", selected: false },
    { value: "Agronomia", text: "Agronomia", selected: false },
    { value: "Veterinaria", text: "Medicina Veterinária", selected: false },
    { value: "Musica", text: "Música", selected: false },
    { value: "Teatro", text: "Teatro", selected: false },
    { value: "Artes", text: "Artes", selected: false },
    { value: "Fotografia", text: "Fotografia", selected: false },
    { value: "Jornalismo", text: "Jornalismo", selected: false },
    { value: "Idiomas_Estrangeiros", text: "Idiomas Estrangeiros", selected: false },
    { value: "Pedagogia", text: "Pedagogia", selected: false },
    { value: "Design_Grafico", text: "Design Gráfico", selected: false },
    { value: "Design_UX_UI", text: "Design UX/UI", selected: false },
    { value: "Gastronomia", text: "Gastronomia", selected: false },
    { value: "Turismo", text: "Turismo", selected: false },
    { value: "Publicidade", text: "Publicidade e Propaganda", selected: false },
    { value: "Relacoes_Internacionais", text: "Relações Internacionais", selected: false },
    { value: "Astrofisica", text: "Astrofísica", selected: false },
    { value: "Geologia", text: "Geologia", selected: false },
    { value: "Oceanografia", text: "Oceanografia", selected: false },
    { value: "Biotecnologia", text: "Biotecnologia", selected: false },
    { value: "Engenharia_Software", text: "Engenharia de Software", selected: false },
    { value: "Analise_Dados", text: "Análise de Dados", selected: false },
];

